name: applications

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  avatar_glow: ^3.0.1
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/shopping_cart.PNG
  - assets/unnamed.png
  - assets/img1.png
  - assets/img2.png
  - assets/img3.png


